title: trovl
description: Documentation for the trovl CLI

permalink: pretty

plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
favicon: true

navigation:
  - name: Home
    link: "/trovl/"
  - name: Installation
    link: "/trovl/install/"
  - name: Quickstart
    link: "/trovl/quickstart/"
  - name: Configuration
    link: "/trovl/configuration/"
  - name: Commands
    link: "/trovl/commands/"
    sublist:
      - name: add
        link: "/trovl/cli/trovl_add/"
      - name: apply
        link: "/trovl/cli/trovl_apply/"
      - name: generate
        link: "/trovl/cli/trovl_generate/"
      - name: plan
        link: "/trovl/cli/trovl_plan/"
      - name: remove
        link: "/trovl/cli/trovl_remove/"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
enable_copy_code_button: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
