title: trovl
description: Documentation for the trovl CLI

permalink: pretty

plugins:
  - jekyll-remote-theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: auto
color_scheme: auto

navigation:
  - name: Home
    link: "/trovl/"
  - name: Installation
    link: "/trovl/install/"
  - name: Quickstart
    link: "/trovl/quickstart/"
  - name: Configuration
    link: "/trovl/configuration/"
  - name: Commands
    link: "/trovl/commands/"
    sublist:
      - name: add
        link: "/trovl/cli/trovl_add/"
      - name: apply
        link: "/trovl/cli/trovl_apply/"
      - name: plan
        link: "/trovl/cli/trovl_plan/"
      - name: remove
        link: "/trovl/cli/trovl_remove/"

defaults:
  - scope:
      path: ""
    values:
      layout: default
