title: trovl
description: Documentation for the trovl CLI

permalink: pretty

plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
favicon: true

navigation:
  - name: Home
    link: "/trovl/"
  - name: Installation
    link: "/trovl/install/"
  - name: Quickstart
    link: "/trovl/quickstart/"
  - name: Configuration
    link: "/trovl/configuration/"
  - name: Commands
    link: "/trovl/commands/"
    sublist:
      - name: add
        link: "/trovl/cli/trovl_add/"
      - name: apply
        link: "/trovl/cli/trovl_apply/"
      - name: generate
        link: "/trovl/cli/trovl_generate/"
      - name: plan
        link: "/trovl/cli/trovl_plan/"
      - name: remove
        link: "/trovl/cli/trovl_remove/"

compress_html:
  ignore:
    envs: all

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
enable_copy_code_button: true

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

defaults:
  - scope:
      path: ""
    values:
      layout: default

footer_content: 'Copyright &copy; 2026 Sneha De. Distributed by an <a href="https://github.com/sneha-afk/trovl/blob/main/LICENSE">MIT license.</a>'
gh_edit_repository: "https://github.com/sneha-afk/trovl"
gh_edit_link: true
gh_edit_branch: "main"
gh_edit_source: docs

aux_links_new_tab: true
aux_links:
  "GitHub":
    - "https://github.com/sneha-afk/trovl"
