title: trovl
description: Documentation for the trovl CLI
url: https://sneha-afk.github.io/trovl/

permalink: pretty

plugins:
  - jekyll-remote-theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: auto

navigation:
  - name: Home
    link: /
  - name: Installation
    link: /installation/
  - name: Quickstart
    link: /quickstart/
  - name: Commands
    link: /commands/
    sublist:
      - name: add
        link: /cli/trovl_add/
      - name: apply
        link: /cli/trovl_apply/
      - name: plan
        link: /cli/trovl_plan/
      - name: remove
        link: /cli/trovl_remove/

defaults:
  - scope:
      path: ""
    values:
      layout: default
